# This file was generated by @liquid-labs/sdlc-projects-workflow-local-node-build.
# Refer to https://npmjs.com/package/@liquid-labs/sdlc-projects-workflow-local-
# node-build for further details

#####
# build dist/site-outage-reporter.cjs
#####

SDLC_SITE_OUTAGE_REPORTER_CJS:=$(DIST)/site-outage-reporter.cjs
SDLC_SITE_OUTAGE_REPORTER_CJS_ENTRY=$(SRC)/lib/index.mjs
BUILD_TARGETS+=$(SDLC_SITE_OUTAGE_REPORTER_CJS)

$(SDLC_SITE_OUTAGE_REPORTER_CJS): package.json $(SDLC_ALL_NON_TEST_JS_FILES_SRC)
	JS_BUILD_TARGET=$(SDLC_SITE_OUTAGE_REPORTER_CJS_ENTRY) \
	  $(SDLC_ROLLUP) --config $(SDLC_ROLLUP_CONFIG)

#####
# end dist/site-outage-reporter.cjs
#####
